# The joint state controller handles publishing transforms for any moving joints
type: "joint_state_controller/JointStateController"
publish_rate: 50

left_steering_ctrlr:
  joint: front_left_wheel_joint
  type: effort_controllers/JointPositionController
  pid: {p: 4.0, i: 0.0, d: 1.0}

right_steering_ctrlr:
  joint: front_right_wheel_joint
  type: effort_controllers/JointPositionController
  pid: {p: 4.0, i: 0.0, d: 1.0}


left_front_wheel:
  steering_link_name: front_left_wheel
  steering_controller_name: left_steering_ctrlr
  diameter: 0.14605

right_front_wheel:
  steering_link_name: front_right_wheel
  steering_controller_name: right_steering_ctrlr
  diameter: 0.14605
